# Generated by Django 5.1.3 on 2024-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('published_date', models.DateField(verbose_name='Data de Publicação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('pages', models.IntegerField(verbose_name='Páginas')),
            ],
            options={
                'verbose_name': 'Livro',
                'ordering': ['title'],
            },
        ),
    ]
